name: Playwright Tests

on:
    pull_request:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 30

        steps:
        - uses: actions/checkout@v4

        - name: Setup .NET
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '8.0.x'

        - name: Install dependencies
          run: dotnet restore

        - name: Build
          run: dotnet build --no-restore

        - name: Install Playwright
          run: pwsh src/UDS.Net.Web.MVC.Services.Test/bin/Debug/net8.0/playwright.ps1 install --with-deps

        - name: Run tests
          run: dotnet test src/UDS.Net.Web.MVC.Services.Test --no-build --verbosity normal