name: Playwright Tests

on:
    repository_dispatch:
        types: [playwright]
    # schedule:
    #   - cron: '30 6 * * 1-5'

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 30

        steps:
        - uses: actions/checkout@v4

        - name: Setup .NET
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '8.0.x'

        - name: Build
          run: dotnet build src/UDS.Net.Web.MVC.Services.Test

        - name: Install Playwright
          run: pwsh src/UDS.Net.Web.MVC.Services.Test/bin/Debug/net8.0/playwright.ps1 install --with-deps

        - name: Run tests
          run: dotnet test src/UDS.Net.Web.MVC.Services.Test --no-build --verbosity normal